### ISSUE TITLE
"Could not convert string to integer: SPE. Path 'region_code', line 6, position 24."

### ISSUE THREAD

**Issue by mcdis** [ipdata/dotnet#1]
Result deserialization failed.
throw exception after Lookup call

Please fix IpInfo:
```
 [JsonProperty("region_code", NullValueHandling = NullValueHandling.Ignore)]
        public string RegionCode { get; set; }
```
RegionCode should be '**string**' instead of '**int?**'

**Comment by alexkhil** [comment]
Hi, @mcdis 

I've already fixed this issue on release v1.1.0
Could you update your package and check on your side?
I'll close the issue in case all is OK.

Thank you, for reporting an issue.
