### ISSUE TITLE
C# Example using a variable instead of hard coded numbers

### ISSUE THREAD

**Issue by studysession** [ipdata/dotnet#11]
Hi -
On the screen I was able to parse through a list of IP's and Domain names formatted like your hard coded example. Could/Would you please give an example making this work? 

`string newFormat = "1.1.1.1", "2.2.2.2", "3.3.3.3", "8.8.8.8"`

`// hard coded example from your page`
`var ipInfoList = await client.Lookup(new string[] { "1.1.1.1", "2.2.2.2", "3.3.3.3" });`
`// using formatted string from variable`
`var ipInfoList = await client.Lookup(new string[] { newFormat });`

Any help at all would be appreciated.
Thanks - Keith

**Comment by alexkhil** [comment]
Hi @studysession 

In case you want introduce hard coded value to variable you can achieve this in few ways:
`var ips = new [] { "1.1.1.1", "2.2.2.2", "3.3.3.3" };`
`var ipInfoList = await client.Lookup(ips);`
or 
`var ips = "1.1.1.1,2.2.2.2,3.3.3.3";`
`var ipInfoList = await client.Lookup(ips.Split(','));`

Is it answer for your question?

**Comment by studysession** [comment]
Thank you
