### ISSUE TITLE
ASN Field from API has changed

### ISSUE THREAD

**Issue by jonathan-kosgei** [ipdata/dotnet#5]
**Describe the bug**
The ASN field returned from the API has changed to an object type. The library expects a string which causes it to break.

**Comment by alexkhil** [comment]
Hi @jonathan-kosgei

Checkout [v2.0.0](https://github.com/alexkhil/IpData/releases/tag/v2.0.0)

Thanks.

**Comment by jonathan-kosgei** [comment]
Thanks for fixing this! I'd love to get in touch about the project, where can I reach you? Alternatively, please send me an email at jonathan@ipdata.co. Thanks again for creating this project!
